### PR TITLE
The cloned page of youtube

### PR DESCRIPTION
**Pull request by 8Bts**
Initial commit was made at featureBranch, but after getting spaghetti code we created feature-2 branch and rebuild our project there

### CODE REVIEW

**Comment by thsvr** [comment]
### **STATUS: CHANGES REQUIRED** :+1: :+1: 

Hi @8Bts and @theshauryasingh :smiley_cat: :smiley_cat: 

Congrats for the hard work, you guys are almost there :smile: :smile: 
Below, there are a few necessary  adjusts necessary for approving your project, so please read them carefully, do the changes and then, ask for another review :+1: :+1: 

:v: On the rightmost part of the navbar, you have to include at least three embedded images that represent icons and/or an avatar, like the original:

### **ORIGINAL:**
yt-original

:v: The style has to be on the css file, not on the html file and you guys have some style on the html code. Can you please fix it?

:v: There are a big margin on your project and it does not look like the original page. Can you please adjust it? 
yt-student

:v: Please, before submit for another review, please check the code on the [validator w3c](https://validator.w3.org/) There are some errors that need to be fixed.


### Optional Suggestions for the next project:

:v:  You can create a feature branch with a more descriptive name on the next projects, like ''main-page'' or ''youtube-main'' instead of ''feature", for example. It will be more descriptive :smile: 

If you have any questions, don't hesitate to contact me through slack @Thaís Vieira Azevedo

### **Happy coding and good luck on the next review** :computer:  

_Project reviewed by Thaís Vieira (TSE)_

**Comment by 8Bts** [comment]
Thanks for the review @thsvr. We fixed all 4 issues and requested for another code review.

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — APPROVED** [review]
## Status: Approved :trophy: :balloon:

Hi **TEAM**, Congratulations, your project looks great 👍 You fixed all the requested changes pointed out by the previous TSE 😄 On this note, I hereby approve of your project. Before we merge to master, let us kindly address these issues
[OPTIONAL]
* Improve README to reflect the current project. Check the link and screenshot. Also, remove sub-titles that are not needed under this project. Kindly add email to the author section
* Consider the width of the main sections and the sidebar as compared to the original

Good luck with your next projects
_Happy coding_ 👨‍💻 
Daniel Larbi Addo

**Comment by 8Bts** [comment]
Thanks for review @addod19. We also fixed the optional issues you mentioned.

**Pull request merged**
